openapi: 3.1.0
info:
  title: Booking API
  description: >
    The Booking API manages movie booking processes, allowing users to view, create, and manage their movie bookings. This API facilitates easy and efficient interactions for booking movies.
  contact:
    email: zineddine.chalekh@imt-atlantique.net, matthis.bleuet@imt-atlantique.net
  license:
    name: GNU General Public License v3 (GPL-3)
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0

tags:
  - name: developers
    description: Operations available to regular developers

paths:
  /:
    get:
      tags:
        - developers
      summary: Home Page
      description: Displays a welcome message for the Booking service.
      responses:
        "200":
          description: Successful response with a welcome message.
          content:
            text/html:
              schema:
                type: string
                example: "<h1 style='color:blue'>Welcome to the Booking service!</h1>"

  /bookings:
    get:
      tags:
        - developers
      summary: Get All Bookings
      description: Retrieves a list of all movie bookings.
      responses:
        "200":
          description: Successful response with a list of bookings.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllBookings'

  /bookings/{userid}:
    get:
      tags:
        - developers
      summary: Get Bookings for User
      description: Retrieves bookings for a specific user by their user ID.
      parameters:
        - in: path
          name: userid
          required: true
          schema:
            type: string
          description: Unique identifier of the user.
      responses:
        "200":
          description: Bookings of the specified user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingsUser'
        "404":
          description: No bookings found for this user.
    post:
      tags:
        - developers
      summary: Add Booking for User
      description: Adds a new booking for a user. Validates the movie availability on the given date.
      parameters:
        - in: path
          name: userid
          required: true
          schema:
            type: string
          description: Unique identifier of the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBooking'
      responses:
        "200":
          description: Booking successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingConfirmation'
        "400":
          description: Invalid data format or date.
        "404":
          description: Movie not available on this date.
        "409":
          description: Booking already exists for the given date.

components:
  schemas:
    AllBookings:
      type: array
      items:
        $ref: '#/components/schemas/BookingsUser'
    BookingsUser:
      type: object
      required:
        - userid
        - dates
      properties:
        userid:
          type: string
          example: user123
        dates:
          type: array
          items:
            $ref: '#/components/schemas/DateItem'
    DateItem:
      type: object
      required:
        - date
        - movies
      properties:
        date:
          type: string
          example: "20230101"
        movies:
          type: array
          items:
            type: string
            example: "39ab85e5-5e8e-4dc5-afea-65dc368bd7ab"
    NewBooking:
      type: object
      required:
        - date
        - movieid
      properties:
        date:
          type: string
          example: "20230101"
        movieid:
          type: string
          example: "39ab85e5-5e8e-4dc5-afea-65dc368bd7ab"
    BookingConfirmation:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Booking successfully added."
