openapi: 3.1.0
info:
  title: Showtime API
  description: API for managing and retrieving movie showtimes, allowing users to view showtimes by date.
  contact:
    email: zineddine.chalekh@imt-atlantique.net, matthis.bleuet@imt-atlantique.net
  license:
    name: GNU General Public License v3 (GPL-3)
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
  - name: developers
    description: Operations available to regular developers

paths:
  /:
    get:
      tags:
        - developers
      summary: Home Page
      description: Displays a welcome message for the Showtime service.
      operationId: home
      responses:
        "200":
          description: Welcome message displayed.
          content:
            text/html:
              schema:
                type: string
                example: "<h1 style='color:blue'>Welcome to the Showtime service!</h1>"

  /showtimes:
    get:
      tags:
        - developers
      summary: Get All Showtimes
      description: Retrieves a list of all showtimes.
      operationId: get_schedule
      responses:
        "200":
          description: Successful response with a list of showtimes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleList'

  /showmovies/{date}:
    get:
      tags:
        - developers
      summary: Get Showtimes by Date
      description: Retrieves the schedule of movies for a specific date.
      operationId: get_movies_by_date
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
          description: The specific date to retrieve showtimes for, formatted as YYYYMMDD.
      responses:
        "200":
          description: Schedule for the specified date.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: Bad input parameter, invalid date format.

components:
  schemas:
    ScheduleList:
      type: array
      items:
        $ref: '#/components/schemas/Schedule'

    Schedule:
      type: object
      required:
        - date
        - movies
      properties:
        date:
          type: string
          example: "20151130"
        movies:
          type: array
          items:
            type: string
            example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
